import crypto from "crypto";

export const coordinates_array = [
    "h1",
    "g1",
    "f1",
    "e1",
    "d1",
    "c1",
    "b1",
    "a1",
    "h2",
    "g2",
    "f2",
    "e2",
    "d2",
    "c2",
    "b2",
    "a2",
    "h3",
    "g3",
    "f3",
    "e3",
    "d3",
    "c3",
    "b3",
    "a3",
    "h4",
    "g4",
    "f4",
    "e4",
    "d4",
    "c4",
    "b4",
    "a4",
    "h5",
    "g5",
    "f5",
    "e5",
    "d5",
    "c5",
    "b5",
    "a5",
    "h6",
    "g6",
    "f6",
    "e6",
    "d6",
    "c6",
    "b6",
    "a6",
    "h7",
    "g7",
    "f7",
    "e7",
    "d7",
    "c7",
    "b7",
    "a7",
    "h8",
    "g8",
    "f8",
    "e8",
    "d8",
    "c8",
    "b8",
    "a8",
];
export const bitCoordinates_array = [
    "7",
    "6",
    "5",
    "4",
    "3",
    "2",
    "1",
    "0",
    "15",
    "14",
    "13",
    "12",
    "11",
    "10",
    "9",
    "8",
    "23",
    "22",
    "21",
    "20",
    "19",
    "18",
    "17",
    "16",
    "31",
    "30",
    "29",
    "28",
    "27",
    "26",
    "25",
    "24",
    "39",
    "38",
    "37",
    "36",
    "35",
    "34",
    "33",
    "32",
    "47",
    "46",
    "45",
    "44",
    "43",
    "42",
    "41",
    "40",
    "55",
    "54",
    "53",
    "52",
    "51",
    "50",
    "49",
    "48",
    "63",
    "62",
    "61",
    "60",
    "59",
    "58",
    "57",
    "56",
];

// stalemate 2 kings remaining
export const moves_stalemate = [
                "d2d3",
                "d7d6",
                "e2e4",
                "c7c5",
                "a2a3",
                "a7a6",
                "g1f3",
                "g8f6",
                "g2g3",
                "h7h6",
                "b1c3",
                "d6d5",
                "e4d5",
                "f6d5",
                "c3d5",
                "d8d5",
                "b2b4",
                "c5b4",
                "a3b4",
                "d5f3",
                "d1f3",
                "e7e6",
                "f1g2",
                "b8c6",
                "f3c6",
                "b7c6",
                "g2c6",
                "e8e7",
                "c6a8",
                "c8b7",
                "c1h6",
                "h8h6",
                "a8b7",
                "h6h2",
                "h1h2",
                "g7g6",
                "b7a6",
                "e7f6",
                "h2h6",
                "f8h6",
                "a6c4",
                "h6g7",
                "c4e6",
                "f7e6",
                "f2f4",
                "f6f5",
                "g3g4",
                "f5g4",
                "c2c4",
                "g7a1",
                "e1f2",
                "g4f4",
                "d3d4",
                "g6g5",
                "f2e2",
                "e6e5",
                "e2d3",
                "a1d4",
                "c4c5",
                "d4c5",
                "b4c5",
                "f4f5",
                "d3e3",
                "f5e6",
                "e3f3",
                "e6d5",
                "f3g4",
                "d5c5",
                "g4g5",
                "c5b4",
                "g5f5",
                "e5e4",
                "f5e4",
            ];


export function generateRandomHash() {
    // Generate a random number (64-bit) using Node.js crypto
    const randomBytes = crypto.randomBytes(8);
    const randomNumber = randomBytes.readBigUInt64LE();

    // Convert the random number to a hexadecimal string
    const randomHex = randomNumber.toString(16);

    // Get the current timestamp in milliseconds
    const timestamp = Date.now().toString();

    // Append the timestamp to the random hexadecimal string
    const combinedString = randomHex + timestamp;

    // Create a hash (SHA-256) from the combined string
    const hash = crypto.createHash("sha256").update(combinedString).digest("hex");

    return hash;
}
